version: '3.9'

services:
  scratchpad:
    build: .
    user: root
    container_name: scratchpad
    #privileged: true
    ports:
      - "9001:8888"
      - "8000:8000"
      - "8265:8265"
      - "8090:8090"
      - "8100:8100"
    restart: "no"
    volumes:
      - ./notebooks:/scratchpad/notebooks
      - ./src:/scratchpad/src
      - ./svcs:/scratchpad/svcs
      - ./data:/scratchpad/data
      - ./codeserver_extensions:/scratchpad/codeserver_extensions
      - ./installers:/scratchpad/installers
      # - ./data/conda_envs/envs:/opt/conda/envs
      # - ./data/conda_envs/pkgs:/opt/conda/pkgs

    # entrypoint:
    #  - bash
    # command:
    #   - -c
    #   - |
    #     jupyter lab --port=8888 --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='' --NotebookApp.password='' -y       
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]