version: '3'

services:
  scratchpad:
    build: .
    user: root
    container_name: scratchpad
    #privileged: true
    ports:
      - "9001:8888"
      - "8000:8000"
      - "8265:8265"
      - "8090:8090"
      - "8100:8100"
      - "6379:6379"    
    volumes:
      - ./notebooks:/scratchpad/notebooks
      - ./src:/scratchpad/src
      - ./svcs:/scratchpad/svcs
      - ./data:/scratchpad/data
      - ./codeserver_extensions:/scratchpad/codeserver_extensions
      - ./installers:/scratchpad/installers
      - ./ghmount:/scratchpad/ghmount
      # - ./data/conda_envs/envs:/opt/conda/envs
      # - ./data/conda_envs/pkgs:/opt/conda/pkgs    
    restart: "no"
    # entrypoint:
    #  - bash
    # command:
    #   - -c
    #   - |
    #     jupyter lab --port=8888 --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='' --NotebookApp.password='' -y       
    deploy:
      resources:
        # limits:
        #   nvidia.com/gpu: "0.5" # requesting 1 GPU
        reservations:
            devices:
              - driver: nvidia
                capabilities: [gpu]
                #count: 1       
  worker_node_a:
    build: 
      context: .
      dockerfile: Dockerfile_worker_node
    user: root
    ports:
      - "9002:8888"
    depends_on:
      - scratchpad
    #container_name: worker_node
    restart: "no"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: "2G"
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              #count: 1
    volumes:
      - ./notebooks:/scratchpad/notebooks
      - ./src:/scratchpad/src
      - ./svcs:/scratchpad/svcs
      - ./data:/scratchpad/data
      - ./codeserver_extensions:/scratchpad/codeserver_extensions
      - ./installers:/scratchpad/installers
      - ./ghmount:/scratchpad/ghmount
      # - ./data/conda_envs/envs:/opt/conda/envs
      # - ./data/conda_envs/pkgs:/opt/conda/pkgs
  worker_node_b:
    #build: 
    image: scratchpad-worker_node_a
    pull_policy: never
    depends_on:
      - worker_node_a
    user: root
    ports:
      - "9003:8888"      
    #container_name: worker_node
    restart: "no"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: "1G"
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              #count: 1
    volumes:
      - ./notebooks:/scratchpad/notebooks
      - ./src:/scratchpad/src
      - ./svcs:/scratchpad/svcs
      - ./data:/scratchpad/data
      - ./codeserver_extensions:/scratchpad/codeserver_extensions
      - ./installers:/scratchpad/installers
      - ./ghmount:/scratchpad/ghmount
      # - ./data/conda_envs/envs:/opt/conda/envs
      # - ./data/conda_envs/pkgs:/opt/conda/pkgs

#docker buildx build -f Dockerfile_worker_node -t worker_node .